language: python
python:
  - "2.6"
  - "2.7"
install:
  pip install -r requirements.txt ; pip install flake8
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then flake8 src/signalfx_metadata.py; fi
script: 
  for x in src/*.py; do python $x once; done
